#!/bin/sh
mkdir -p $HOME/.local/bin
mkdir -p $HOME/.local/source

alias gc='git clone --depth 1'

if [[ ! `uname -r` == *WSL* ]]; then
	pushd $HOME/.local/source
	gc https://github.com/racagogi/kime
	gc https://github.com/YaLTeR/niri
	gc https://github.com/LGFae/swww
	gc https://github.com/raphamorim/rio.git
	gc https://github.com/wezterm/wezterm
	popd
fi

if ! command -v rustup 2>&1 >/dev/null
then
	curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
	. "$HOME/.cargo/env"
fi

cargo install sccache          

export RUSTC_WRAPPER=sccache
export CC="sc-gcc"
export CXX="sc-g++"

cargo install bottom           
cargo install cargo-update     
cargo install du-dust          
cargo install eza              
cargo install fd-find          
cargo install fnm              
cargo install ripgrep          
cargo install starship         
cargo install tokei            
cargo install tree-sitter-cli  
cargo install typst-cli        
cargo install vivid            
cargo install zoxide           
